# Site settings
title: SatyamVyas04
author:
    name: Satyam Vyas
    email: vyas.satyam.04@gmail.com
description: "Some insight on me @SatyamVyas04"

# Build settings
theme: just-the-docs

# Markdown settings
markdown: kramdown
highlighter: rouge

# Permalink Settings
defaults:
    - scope:
          path: "" # empty string for all files
          type: "README"
      values:
          permalink: /
