name: Update Index

on:
    schedule:
        - cron: "0 0 * * *" # Runs every day at midnight
    workflow_dispatch: # Allows manual triggering of the workflow

jobs:
    update-index:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Copy README.md to index.md with YAML front matter
              run: |
                  echo "---" > index.md
                  echo "layout: default" >> index.md
                  echo "title: home" >> index.md
                  echo "---" >> index.md
                  echo "" >> index.md
                  cat README.md >> index.md

            - name: Commit and push changes
              run: |
                  git config --local user.name "github-actions[bot]"
                  git config --local user.email "github-actions[bot]@users.noreply.github.com"
                  git add index.md
                  git commit -m "Update index.md from README.md"
                  git push
